baseURL = "https://www.wimdeblauwe.com/"
languageCode = "en-us"
title = "Wim Deblauwe"
theme = "ezhil"
copyright = "Â© 2022 Wim Deblauwe"
# disqusShortname = ""
googleAnalytics = "G-VJZ8LM94JG"

[params]
    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site
    featherIconsCDN = true
    customCSS = "css/wimdeblauwe.css"
    images = ['images/wim-deblauwe.jpg']

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Books"
url = "/books"
weight = 3

[[menu.main]]
name = "Conferences"
url = "/conferences"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[params.social]]
name = "RSS FEED"
icon = "rss"
url = "/blog/index.xml"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/wimdeblauwe"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/wimdeblauwe"

# Enable tags.
[taxonomies]
tag = "tags"

[privacy.youtube]
privacyEnhanced = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[security]
enableInlineShortcodes = false

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[security.funcs]
getenv = ['^HUGO_']

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
